### ISSUE TITLE
syntax highlighting only working for rust

### ISSUE THREAD

**Issue by ettoreleandrotognoli** [cognitive-engineering-lab/mdbook-quiz#25]
I'm having this waning log:

```
Could not find the language 'cpp', did you forget to load/include a language module? [lib.js:152:25938](http://localhost:3000/quiz/lib.js)
Falling back to no-highlight mode for this block. 
<code class="language-cpp">
[lib.js:152:25973](http://localhost:3000/quiz/lib.js)
```

My question:
````toml
[[questions]]
type = "MultipleChoice"
prompt.prompt = """
```cpp
int x = 0;
```
"""
````

I have the same error with python too.
I think it is because the code only imports rust:

https://github.com/cognitive-engineering-lab/mdbook-quiz/blob/b0002743133a57507878a72262a1281ff3e54af0/js/packages/quiz/src/components/snippet.tsx#L6

And indeed for rust the highlight is working
